org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-integrateddynamics
addon_name=BlueMap Integrated Dynamics Add-on
addon_version=0.1.0-alpha.3
addon_group=io.github.jan-guenter
artifact_id=bluemap-integrated-dynamics-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=57598
accepted_jar_sha256=a82e8224360da54fab12d94a53408fb53e1f334c6e2b885e594cd50ed23ba828
