org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-integrateddynamics
addon_name=BlueMap Integrated Dynamics Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-integrated-dynamics-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=51482
accepted_jar_sha256=abbc6e4e910572a88323856d153d16cc7909542c553b2be0d89b5c2aa7d77b32
