org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-integrateddynamics
addon_name=BlueMap Integrated Dynamics Add-on
addon_version=0.1.0-alpha.4
addon_group=io.github.jan-guenter
artifact_id=bluemap-integrated-dynamics-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=58352
accepted_jar_sha256=d6dcf7682244189d653708310b0a86d89d236f5be9f38d6f99f06371aa6e88f0
